### ISSUE TITLE
关于评价指标MIOU

### ISSUE THREAD

**Issue by hhh200191** [BingqiangZhou/SalientObjectDetection#1]
大佬你好，请问哪里用到了评价指标MIOU啊？

**Comment by BingqiangZhou** [comment]
U2Net/U2NetPy/u2net_val.py中

**Comment by BingqiangZhou** [comment]
https://github.com/BingqiangZhou/SalientObjectDetection/blob/master/U2Net/U2NetPy/u2net_val.py

**Comment by hhh200191** [comment]
找到了，十分感谢。
